name: Rainix CI
on: [push]

concurrency:
  group: ${{ github.ref }}-rainix
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  standard-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        task: [rainix-rs-test, rainix-rs-artifacts]
        include:
          # We don't need to do rust static analysis on multiple platforms
          - os: ubuntu-latest
            task: rainix-rs-static
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_POLYGON_RPC: ${{ secrets.CI_DEPLOY_POLYGON_RPC_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 5G

      - run: nix develop -c rainix-rs-prelude
      - name: Run ${{ matrix.task }}
        run: nix develop -c ${{ matrix.task }}

      - name: Build for wasm target
        run: nix develop -c cargo build --target wasm32-unknown-unknown
