name: rainix-rs
on: [push]
jobs:
  static:
    uses: rainlanguage/rainix/.github/workflows/rainix-rs-static.yaml@main
  test:
    uses: rainlanguage/rainix/.github/workflows/rainix-rs-test.yaml@main
  wasm:
    uses: rainlanguage/rainix/.github/workflows/rainix-rs-wasm.yaml@main
